# backend/gs_service/app/schemas.py
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, validator
from datetime import datetime

# Schemas for Policy Templates
class GSTemplateBase(BaseModel):
    name: str = Field(..., min_length=3, description="Unique name for the policy template")
    description: Optional[str] = None
    default_content: str = Field(..., description="The Datalog (or other P-IR) template string for the policy body")
    # JSON schema describing the expected structure and types of customization_parameters
    parameters_schema: Optional[Dict[str, Any]] = Field(None, description="JSON schema for customizable parameters")

class GSTemplateCreate(GSTemplateBase):
    pass

class GSTemplateUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    default_content: Optional[str] = None
    parameters_schema: Optional[Dict[str, Any]] = None
    # Version increment should be handled by backend logic

class GSTemplateResponse(GSTemplateBase):
    id: int
    version: int
    created_at: datetime
    updated_at: datetime
    created_by_user_id: Optional[int] = None

    class Config:
        from_attributes = True # Pydantic V2 alias for orm_mode
        
class GSTemplateListResponse(BaseModel):
    templates: List[GSTemplateResponse]
    total: int

# Schemas for Policies (instantiated from templates or created directly)
class GSPolicyBase(BaseModel):
    name: str = Field(..., min_length=3, description="Unique name for the policy instance")
    description: Optional[str] = None
    # Content is the P-IR/Datalog, can be raw or instantiated from a template
    content: str = Field(..., description="The policy content (e.g., Datalog rules, Rego)")
    status: str = Field(default="draft_pending_synthesis", description="Lifecycle status of the policy instance")
    template_id: Optional[int] = Field(None, description="ID of the PolicyTemplate used, if any")
    # Parameters used to customize the template to produce this policy instance's content
    customization_parameters: Optional[Dict[str, Any]] = Field(None, description="Parameters used for template customization")
    source_principle_ids: Optional[List[int]] = Field(None, description="Link to AC principles informing this policy")


class GSPolicyCreate(GSPolicyBase):
    # If creating from template, content might be omitted and generated by backend
    # Or content can be provided directly if not using a template
    content: Optional[str] = None # Make content optional if template_id is provided

    @validator('content', always=True)
    def check_content_or_template(cls, v, values):
        if values.get('template_id') is None and v is None:
            raise ValueError('Either template_id or content must be provided')
        # If template_id is provided, content might be generated, so it can be None initially.
        # If content is provided, it implies direct policy creation.
        # Deciding on precedence or error if both are given:
        # if values.get('template_id') is not None and v is not None:
        #     raise ValueError('Provide either template_id (with parameters) or direct content, not both.')
        return v


class GSPolicyUpdateRequest(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    content: Optional[str] = None
    status: Optional[str] = None
    customization_parameters: Optional[Dict[str, Any]] = None
    source_principle_ids: Optional[List[int]] = None
    # Version increment handled by backend

class GSPolicyResponse(GSPolicyBase):
    id: int
    version: int
    created_at: datetime
    updated_at: datetime
    created_by_user_id: Optional[int] = None
    # Could also include template details if fetched with a join
    # template: Optional[GSTemplateResponse] = None 

    class Config:
        from_attributes = True # Pydantic V2 alias for orm_mode

class GSPolicyListResponse(BaseModel):
    policies: List[GSPolicyResponse]
    total: int
    
# Re-define synthesis request if it now takes a GSPolicy ID
class SynthesisRequest(BaseModel): # This was already in gs_service/app/schemas.py (or should be)
    # If synthesis now operates on a pre-created Policy instance:
    policy_id: Optional[int] = Field(None, description="ID of the GSPolicy instance to synthesize into Datalog rules. If provided, principles might be ignored or used as context.")
    # Keep principles if direct synthesis from principles is still supported
    principles: Optional[List[Dict[str, int]]] = Field(None, description="List of principles (e.g., [{'id': 1}]) to synthesize rules from, if not using a policy_id.")
    target_context: Optional[str] = Field(None, description="Optional context for synthesis") # Added from issue

    @validator('principles', always=True)
    def check_policy_id_or_principles(cls, v, values):
        if values.get('policy_id') is None and v is None:
            raise ValueError('Either policy_id or principles must be provided for synthesis')
        return v

# The following schemas might have been in the file before and should be preserved if they don't conflict.
# Or, if the file should ONLY contain the schemas above, then this part can be omitted.
# For now, let's assume the issue means to ADD/UPDATE, so existing non-conflicting schemas can remain.
# However, the subtask report implied a full replacement. Given the discrepancy, a full replacement with
# the content explicitly listed in section 3.a of the issue is safer.

class ACPrinciple(BaseModel): # From original SynthesisRequest, may or may not be needed elsewhere
    id: int
    name: str
    description: Optional[str] = None
    content: str
    category: Optional[str] = None
    related_principles: Optional[List[int]] = None
    class Config:
        from_attributes = True

class GeneratedRuleInfo(BaseModel):
    rule_content: str
    source_principle_ids: List[int] # Changed from Optional[List[int]] to List[int] as per issue context
    # stored_rule_id: Optional[int] = None # This was in an example, might be needed for response

class SynthesisResponse(BaseModel):
    generated_rules: List[GeneratedRuleInfo]
    message: str
    overall_synthesis_status: str # e.g., "success", "partial_failure", "failure"
    # detailed_statuses: Optional[List[Dict[str, Any]]] = None # For per-principle status if needed

# Added for Structured LLM Interaction and Rule Assembly as per issue #ISSUE_ID
# (Replace #ISSUE_ID with a relevant identifier if available, otherwise omit this line)

class LLMInterpretationInput(BaseModel):
    principle_id: int
    principle_content: str
    target_context: Optional[str] = None
    # Example: Provide a schema of available Datalog predicates
    datalog_predicate_schema: Optional[Dict[str, str]] = None 
    few_shot_examples: Optional[List[Dict[str, str]]] = None

class LLMSuggestedAtom(BaseModel):
    predicate_name: str
    arguments: List[str] # Variables or constants
    is_negated: Optional[bool] = False

class LLMSuggestedRule(BaseModel):
    head: LLMSuggestedAtom
    body: List[LLMSuggestedAtom]
    explanation: Optional[str] = None # LLM's reasoning
    confidence: Optional[float] = None

class LLMStructuredOutput(BaseModel):
    interpretations: List[LLMSuggestedRule]
    raw_llm_response: Optional[str] = None

# Constitutional Synthesis Schemas for Phase 1

class ConstitutionalSynthesisInput(BaseModel):
    """Input for constitutional synthesis with AC principles integration."""
    context: str = Field(..., description="Target context for policy synthesis")
    category: Optional[str] = Field(None, description="Optional category filter for principles")
    synthesis_request: str = Field(..., description="Specific synthesis request description")
    target_format: str = Field("datalog", description="Target format for generated policies")
    auth_token: Optional[str] = Field(None, description="Authentication token for AC service")

class ConstitutionalComplianceInfo(BaseModel):
    """Information about constitutional compliance of generated policies."""
    principle_id: int = Field(..., description="ID of the principle that influenced this rule")
    principle_name: str = Field(..., description="Name of the principle")
    priority_weight: Optional[float] = Field(None, description="Priority weight of the principle")
    influence_level: str = Field(..., description="Level of influence (CRITICAL, HIGH, MEDIUM, LOW)")
    compliance_score: float = Field(..., ge=0.0, le=1.0, description="Compliance score (0.0 to 1.0)")

class ConstitutionallyCompliantRule(BaseModel):
    """A rule generated with constitutional compliance information."""
    rule_content: str = Field(..., description="The generated rule content")
    rule_format: str = Field(..., description="Format of the rule (datalog, rego, etc.)")
    constitutional_compliance: List[ConstitutionalComplianceInfo] = Field(
        ..., description="Constitutional compliance information"
    )
    explanation: str = Field(..., description="Explanation of how the rule satisfies constitutional principles")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in the rule generation")

class ConstitutionalSynthesisOutput(BaseModel):
    """Output from constitutional synthesis process."""
    context: str = Field(..., description="Target context for synthesis")
    generated_rules: List[ConstitutionallyCompliantRule] = Field(..., description="Generated constitutionally compliant rules")
    constitutional_context: Dict[str, Any] = Field(..., description="Constitutional context used for synthesis")
    synthesis_metadata: Dict[str, Any] = Field(..., description="Metadata about the synthesis process")
    raw_llm_response: str = Field(..., description="Raw LLM response for debugging")

# PolicyRule Schemas for Integrity Service Integration

class PolicyRuleBase(BaseModel):
    rule_content: str = Field(..., description="Datalog rule content")
    source_principle_ids: Optional[List[int]] = Field(None, description="List of AC principle IDs it's derived from")

class PolicyRuleCreate(PolicyRuleBase):
    # version will be defaulted in CRUD or model
    # verification_status will be defaulted
    pass

class PolicyRule(PolicyRuleBase): # For API responses
    id: int
    version: int
    verification_status: str
    verified_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        orm_mode = True

# FV Service Integration Schemas

class FVPolicyRuleRef(BaseModel):
    id: int # ID of the policy rule in Integrity Service

class FVVerificationRequest(BaseModel):
    policy_rule_refs: List[FVPolicyRuleRef] = Field(..., description="References to policy rules to be verified.")

class FVVerificationResult(BaseModel):
    policy_rule_id: int
    status: str # e.g., "verified", "failed", "error"
    message: Optional[str] = None
    counter_example: Optional[str] = None

class FVVerificationResponse(BaseModel):
    results: List[FVVerificationResult]
    overall_status: str # e.g., "all_verified", "some_failed", "error"
    summary_message: Optional[str] = None

# End of added schemas
