"""manual_add_policy_template_tables

Revision ID: 2b1a73c9f5d4
Revises: eaa5f6249b99
Create Date: 2025-05-22 10:10:15.123456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB # Import JSONB

# revision identifiers, used by Alembic.
revision: str = '2b1a73c9f5d4'
down_revision: Union[str, None] = 'eaa5f6249b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('default_content', sa.Text(), nullable=False),
        sa.Column('parameters_schema', JSONB, nullable=True), # Changed to JSONB
        sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_policy_templates_id'), 'policy_templates', ['id'], unique=False)
    # Removed unique=True for ix_policy_templates_name as name itself has UniqueConstraint

    op.create_table('policies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('status', sa.String(), nullable=False, server_default='draft'),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('customization_parameters', JSONB, nullable=True), # Changed to JSONB
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.Column('previous_version_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['previous_version_id'], ['policies.id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['policy_templates.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    # op.drop_index(op.f('ix_policy_templates_name'), table_name='policy_templates') # Removed as name is unique
    op.drop_index(op.f('ix_policy_templates_id'), table_name='policy_templates')
    op.drop_table('policy_templates')
    # ### end Alembic commands ###
