---
apiVersion: v1
kind: Namespace
metadata:
  name: acgs-pgp
  labels:
    name: acgs-pgp
    environment: production
    app.kubernetes.io/name: acgs-pgp
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: acgs-pgp-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: acgs-pgp-quota
  namespace: acgs-pgp
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: acgs-pgp-limits
  namespace: acgs-pgp
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
